### ISSUE TITLE
Requires texlive, which should be optional

### ISSUE THREAD

**Issue by Zireael07** [flathub/ch.theologeek.Manuskript#1]
Cross-ref https://github.com/olivierkes/manuskript/issues/995

The texlive SDK is several GBs big, and apparently only used for PDF export, which not everyone uses (I don't, I export to Markdown)

**Comment by hfiguiere** [comment]
It should be marked as "noautodownload: true"

**Comment by Zireael07** [comment]
Thanks! If I already installed, is there a way for me to somehow remove texlive short of uninstalling the flatpak and reinstalling?
